# Generated by Django 3.2.4 on 2023-02-02 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_detial', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('Awardee', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('G_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Latest_News',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('News', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('L_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_detial', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('categories', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/user_image.png', upload_to='photo/%Y/%m/%d')),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 27583, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_detial', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('P_id', models.IntegerField(primary_key=True, serialize=False)),
                ('list_detial', models.CharField(max_length=200)),
                ('last_updated_date', models.DateField(default=datetime.datetime(2023, 2, 2, 4, 9, 41, 28663, tzinfo=utc))),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
