# Generated by Django 3.2.4 on 2023-02-02 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='Awards/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='Events/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='events',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='Gallery/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 16655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='Team/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default='images/user_image.png', upload_to='Testimonials/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='value',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vision',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 4, 12, 57, 25164, tzinfo=utc)),
        ),
    ]
