# Generated by Django 3.2.4 on 2023-02-03 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230203_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='carrer/Screenshot_3.png', upload_to='photo/%Y/%m/%d')),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Message', models.CharField(default='designation', max_length=200)),
                ('updated_date', models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc))),
                ('Subject', models.CharField(default='department', max_length=200)),
                ('qualififcation', models.CharField(default='qualififcation', max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('bio', models.CharField(default='No Bio yet.', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='awards',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='logo',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mission',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='value',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vision',
            name='last_updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 6, 31, 38, 45134, tzinfo=utc)),
        ),
    ]
